config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  resource :session
  resource :registration
  resource :password_reset
  resource :password

  resources :pages do
    resources :links
  end

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :page
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  has_many :links, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :pages, dependent: :destroy
  has_many :links, through: :pages

  validates :email, presence: true, uniqueness: true

  normalizes :email, with: ->(email) { email.strip.downcase }

  generates_token_for :password_reset, expires_in: 30.minutes do
    password_salt&.last(10)
  end

  generates_token_for :email_confirmation, expires_in: 24.hours do
    email
  end
end

app/controllers/application_controller.rb
require "byebug"

class ApplicationController < ActionController::Base
  private

  def authenticate_user!
    redirect_to root_path, alert: "Vous devez etre connecté pour accéder à cette page." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout
    reset_session
    Current.user = nil
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page
  before_action :set_link, only: %i[show edit update destroy]

  def index
    @links = @page.links
  end

  def show
  end

  def new
    @link = @page.links.new
  end

  def edit
  end

  def create
    @link = @page.links.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to page_link_url(@page.id, @link.id), notice: "Link was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to page_link_url(@page.id, @link.id), notice: "Link was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to page_links_url(@page.id), notice: "Link was successfully destroyed." }
    end
  end

  private

  def set_page
    @page = current_user.pages.find(params[:page_id])
  end

  def set_link
    @link = @page.links.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :source, :page_id)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page, only: %i[ show edit update destroy ]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new
  end

  def edit
  end

  def create
    @page = Page.new(page_params)
    @page.user_id = current_user.id
    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
    end
  end

  private

  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :body)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :load_user_with_token, only: [:edit, :update]

  def new
  end

  def create
    if (user = User.find_by(email: params[:email]))
      token = user.generate_token_for(:password_reset)
      PasswordMailer.with(
        user:,
        token:
      ).password_reset.deliver_later
    end
    redirect_to root_path, notice: 'Un mail de récupération de mot de passe a été envoyé.'
  end

  def edit
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: 'Votre mot de passe a été modifié avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def load_user_with_token
    @user = User.find_by_token_for(:password_reset, params[:token])
    redirect_to new_password_reset_path, alert: 'Le jeton de récupération est invalide, veuillez réessayer' unless @user.present?
  end

  def password_params
    params.require(:user).permit(%w[password password_confirmation])
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :authenticate_user!
  def edit
  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Mot de passe modifié avec succès !"
    else
      flash[:alert] = current_user.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def password_params
    params.require(:user).permit(
      %w[password password_confirmation password_challenge]
    ).with_defaults(password_challenge: "")
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_registration_params)
    if @user.save
      login @user
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_registration_params
    params.require(:user).permit(%w[email password password_confirmation])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if (user = User.authenticate_by(email: params[:email], password: params[:password]))
      login user
      redirect_to root_path, notice: "Connecté."
    else
      flash[:alert] = "Email ou mot de passe incorrect."
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Déconnecté."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treelink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div><%= notice %></div>
    <div><%= alert %></div>
    
    <% if user_signed_in? %>
      <%= link_to 'Modifier mon mot de passe', edit_password_path %>
      <%= button_to 'Déconnexion', session_path, method: :delete %>
    <% else %>
      <%= link_to 'Inscription', new_registration_path %>
      <%= link_to 'Connexion', new_session_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for([page, link]) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :page_id, value: @page.id %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_area :source %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <p>
    <strong>Title:</strong>
    <%= link.title %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= link.source %>
  </p>

  <p>
    <strong>Page:</strong>
    <%= link.page_id %>
  </p>

</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", page: @page, link: @link %>

<br>

<div>
  <%= link_to "Show this link", page_link_path(@page.id, @link.id) %> |
  <%= link_to "Back to links", page_links_path(@page.id) %>
</div>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <% @links.each do |link| %>
    <%= render link %>
    <p>
      <%= link_to "Show this link", page_link_path(@page, link) %>
    </p>
  <% end %>
</div>

<%= link_to "New link", new_page_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render "form", page: @page, link: @link %>

<br>

<div>
  <%= link_to "Back to links", page_links_path(@page.id) %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_page_link_path(@page.id, @link.id) %> |
  <%= link_to "Back to links", page_links_path(@page.id) %>

  <%= button_to "Destroy this link", page_link_path(@page.id, @link.id), method: :delete %>
</div>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <p>
    <strong>Title:</strong>
    <%= page.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= page.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= page.user_id %>
  </p>

</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", @page %> |
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", page %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", pages_path %>
</div>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_page_path(@page) %> |
  <%= link_to "Back to pages", pages_path %>

  <%= button_to "Destroy this page", @page, method: :delete %>
</div>

app/views/password_resets/edit.html.erb
<div>
  <%= form_with model: @user, url: password_reset_path(token: params[:token]) do |f| %>
    <% if f.object.errors.any? %>
      <% f.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    <% end %>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div>
      <%= f.submit "Enregistrer" %>
    </div>
    <% end %>
</div>

app/views/password_resets/new.html.erb
<div>
  <%= form_with model: @user, url: password_reset_path do |f| %>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.submit "Réinitialiser le mot de passe" %>
    </div>
  <% end %>
</div>